import type { Metadata } from 'next'
import './globals.css'
import { readdir } from 'node:fs/promises'
import Link from 'next/link'
import { Button } from '@/components/ui/button'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const dirs = await readdir('./src/app/examples')

  return (
    <html lang="en">
      <body className={`antialiased darko`}>
        <ul className="flex p-1 gap-2">
          <li>
            <Button
              className="p-0 capitalize"
              type="link">
              <Link href={`/`}>ui</Link>
            </Button>
          </li>
          {dirs.map((path) => (
            <li key={path}>
              <Button
                className="p-0 capitalize"
                type="link">
                <Link href={`/examples/${path}`}>{path}</Link>
              </Button>
            </li>
          ))}
        </ul>
        {children}
      </body>
    </html>
  )
}
